// Generated by github.com/podhmo/gos/genum/tools [-write -builder -metadata -to-string -pkgname genum]

package genum

type EnumMetadata struct {
	id         int    // required by reference
	Name       string `json:"-"` // required by reference (and toString)
	underlying string `json:"-"` // required by toString

	Doc string
}

type IntMetadata struct {
	Default int `json:"default"`
	Members []*IntValueMetadata
}

type IntValueMetadata struct {
	Name  string
	Value int
	Doc   string
}

type StringMetadata struct {
	Default string `json:"default"`
	Members []*StringValueMetadata
}

type StringValueMetadata struct {
	Name  string
	Value string
	Doc   string
}
