// Generated by github.com/podhmo/gos/genum/tools [-write -builder -metadata -to-string -pkgname genum]

package genum

import (
	"fmt"
	"io"
	"strings"
)

func (t *_Enum[R]) String() string {
	return ToString(t.ret)
}

func ToString(t EnumBuilder) string {
	b := new(strings.Builder)
	if err := t.writeEnum(b); err != nil {
		return fmt.Sprintf("invalid type: %T", t)
	}
	return b.String()
}

// default implementation or write Enum
func (t *_Enum[R]) writeEnum(w io.Writer) error {
	if t.metadata.Name != "" {
		if _, err := io.WriteString(w, t.metadata.Name); err != nil {
			return err
		}
	} else {
		if _, err := io.WriteString(w, t.metadata.underlying); err != nil {
			return err
		}
	}
	return nil
}
