run-example: router default

default:
	go run ./_examples/ > ./_examples/openapi.json

# simple router example
router:
	go run ./_examples/router > ./_examples/router/openapi.json

.PHONY: run-example router default