openapi: 3.0.3
info:
  title: foo
  version: 0.0.0
components:
  schemas:
    foo:
      properties:
        text:
          type: string
paths:
  /foo/{id}:
    get:
      operationId: getFoo
      description: ""
      parameters:
      - name: verbose
        in: query
        schema:
          type: boolean
      - name: id
        in: path
        required: true
        schema:
          type: string

      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/foo"
    delete:
      operationId: deleteFoo
      description: ""
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string

      responses:
        204:
          description: ""
          content:
            application/json: {}


